import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";

export const GENERATED_GLYPHS_PATH = join(
	import.meta.dir,
	"..",
	"src",
	"chat",
	"generated",
	"providerGlyphs.ts",
);

/**
 * pi provider id → icon slug in `@lobehub/icons-static-svg`. The only place that mapping is written.
 * Vendors reachable through several pi providers (regional variants, token plans, gateways) share
 * one glyph; a provider missing here renders the monogram fallback.
 */
export const PROVIDER_GLYPH_SLUGS: Readonly<Record<string, string>> = {
	anthropic: "claude",
	"ant-ling": "claude",
	openai: "openai",
	"openai-codex": "openai",
	"azure-openai-responses": "azure",
	google: "gemini",
	"google-vertex": "vertexai",
	"amazon-bedrock": "bedrock",
	"github-copilot": "githubcopilot",
	xai: "xai",
	groq: "groq",
	cerebras: "cerebras",
	openrouter: "openrouter",
	"vercel-ai-gateway": "vercel",
	mistral: "mistral",
	deepseek: "deepseek",
	nvidia: "nvidia",
	zai: "zai",
	"zai-coding-cn": "zai",
	minimax: "minimax",
	"minimax-cn": "minimax",
	moonshotai: "moonshot",
	"moonshotai-cn": "moonshot",
	"kimi-coding": "kimi",
	huggingface: "huggingface",
	fireworks: "fireworks",
	together: "together",
	baseten: "baseten",
	opencode: "opencode",
	"opencode-go": "opencode",
	meta: "meta",
	"cloudflare-workers-ai": "cloudflare",
	"cloudflare-ai-gateway": "cloudflare",
	"qwen-token-plan": "qwen",
	"qwen-token-plan-cn": "qwen",
	"qwen-token-plan-individual": "qwen",
	ollama: "ollama",
	lmstudio: "lmstudio",
	perplexity: "perplexity",
};

const require = createRequire(import.meta.url);

function iconsDir(): string {
	return join(dirname(require.resolve("@lobehub/icons-static-svg/package.json")), "icons");
}

/** One `<path>` of a monochrome glyph: its data and, for layered marks, the fill opacity it keeps. */
export interface GlyphPath {
	d: string;
	opacity?: number;
}

export function readGlyphPaths(slug: string, dir = iconsDir()): GlyphPath[] {
	const svg = readFileSync(join(dir, `${slug}.svg`), "utf8");
	if (!/viewBox="0 0 24 24"/.test(svg)) throw new Error(`${slug}.svg is not a 24×24 glyph`);
	if (/<(g|circle|rect|polygon|ellipse|line|defs|clipPath|mask)\b/.test(svg)) {
		throw new Error(`${slug}.svg uses elements other than <path>`);
	}
	if (/ fill="(?!currentColor)/.test(svg)) throw new Error(`${slug}.svg carries its own colours`);
	const paths = [...svg.matchAll(/<path ([^>]*)>/g)].map((match) => {
		const attrs = match[1] ?? "";
		const d = /\bd="([^"]+)"/.exec(attrs)?.[1];
		if (!d) throw new Error(`${slug}.svg has a <path> without data`);
		const opacity = /fill-opacity="([^"]+)"/.exec(attrs)?.[1];
		return opacity === undefined ? { d } : { d, opacity: Number(opacity) };
	});
	if (paths.length === 0) throw new Error(`${slug}.svg contains no <path>`);
	return paths;
}

function identifier(slug: string): string {
	if (!/^[a-z][a-z0-9]*$/.test(slug)) throw new Error(`glyph slug ${slug} is not an identifier`);
	return `glyph_${slug}`;
}

export function renderGlyphsModule(
	slugs: Readonly<Record<string, string>> = PROVIDER_GLYPH_SLUGS,
	read: (slug: string) => GlyphPath[] = readGlyphPaths,
): string {
	const bySlug = new Map<string, GlyphPath[]>();
	for (const slug of new Set(Object.values(slugs))) bySlug.set(slug, read(slug));
	const lines = [
		"// GENERATED by scripts/generate-provider-glyphs.ts from @lobehub/icons-static-svg — do not edit.",
		"// Monochrome 24×24 vendor marks drawn with currentColor and fill-rule evenodd; the logos remain the",
		"// trademarks of their owners.",
		"",
		"export interface ProviderGlyphPath {",
		"\td: string;",
		"\topacity?: number;",
		"}",
		"",
		...[...bySlug.entries()]
			.sort(([a], [b]) => a.localeCompare(b))
			.map(
				([slug, paths]) =>
					`const ${identifier(slug)}: readonly ProviderGlyphPath[] = ${JSON.stringify(paths)};`,
			),
		"",
		"export const PROVIDER_GLYPHS: Readonly<Record<string, readonly ProviderGlyphPath[]>> = {",
		...[...Object.entries(slugs)]
			.sort(([a], [b]) => a.localeCompare(b))
			.map(([provider, slug]) => `\t${JSON.stringify(provider)}: ${identifier(slug)},`),
		"};",
		"",
	];
	return lines.join("\n");
}
